services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - PGDB_HOST=pgdb
      - PGDB_NAME=devdb
      - PGDB_USER=devuser
      - PGDB_PASS=changeme
      - FBDB_HOST=fbdb
      - FBDB_NAME=/firebird/data/test.fdb
      - FGDB_USER=sysdba
      - FGDB_PASS=masterkey
    depends_on:
      - pgdb
      - fbdb

  pgdb:
    image: postgres:17.0
    volumes:
      - /Users/albert/DB/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"

  fbdb:
    image: jacobalberty/firebird:latest
    environment:
      - ISC_PASSWORD=masterkey
    volumes:
 #       - dev-fbdb-data:/firebird/data
        - /Users/albert/DB:/firebird/data
    ports:
        - "3051:3050"

# volumes:
#  dev-pgdb-data:
#  dev-fbdb-data:
